
on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
name: Deploy
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read
jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{secrets.AWS_ROLE_ARN}}
        role-session-name: samplerolesession
        aws-region: ${{secrets.AWS_REGION}}
 
    
    - name: Update kube config
      run: aws eks update-kubeconfig --name ${{secrets.EKS_CLUSTER_NAME}} --region ${{secrets.AWS_REGION}}
    - name: Set image tag
      env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{secrets.ECR_REPO_NAME}}
          
      run: |
        
        cd demo-charts/demo
        echo $ECR_REGISTRY
        echo $ECR_REPOSITORY
        COMMIT_ID=$(echo "${{ github.sha }}" | head -c 5)
        sed -E -i "s/tag: \"(.*)\"/tag: \"${BRANCH_NAME}-${COMMIT_ID}\"/g" values.yaml

        helm lint .
        cat values.yaml
    - name: helm deploy
      run: |
        kubectl get no
        kubectl get po -A
        
        cd demo-charts/demo && helm upgrade --install demo . -f values.yaml 
        kubectl get po
        kubectl get ingress
        INGRESS_URL=$(kubectl get ingress demo -o jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}')
        echo "Application  URL: $INGRESS_URL/assessment/actuator/health"    
