
on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
name: Deploy
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read
jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{secrets.AWS_ROLE_ARN}}
        role-session-name: samplerolesession
        aws-region: ${{secrets.AWS_REGION}}
    
    - name: Update EKS deployment
      id: deploy-eks
      uses: aws-actions/amazon-ecr-login@v1
    - name: Update kube config
      run: aws eks update-kubeconfig --name dob-dev-cluster --region eu-west-1
    - name: Set image tag
      env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}
      run: |
        COMMIT_ID=$(echo "${{ github.sha }}" | head -c 5)
        cd demo-charts/demo
        sed -E -i "s/tag: \"(.*)\"/tag: \"${BRANCH_NAME}-${COMMIT_ID}\"/g" values.yaml
        helm lint .
    - name: helm deploy
      run: |
        cd demo-charts/demo && helm upgrade --install demo . -f values.yaml  --wait    
